name: flutter_authentication
description: A flutter project exemplifying authentication
publish_to: 'none' 

version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  freezed: ^2.1.0+1

  freezed_annotation: ^2.1.0

  async_redux: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0

  flutter_gen_runner: 5.1.0+1

  json_annotation: any

  json_serializable: any

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
