name: flutter_authentication
description: A flutter project exemplifying authentication
publish_to: 'none' 

version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cloud_firestore: ^4.13.0

  freezed: ^2.1.0+1

  freezed_annotation: ^2.1.0

  firebase_auth: ^4.11.1

  firebase_core: ^2.19.0

  flutter_svg: ^2.0.9

  flutter_facebook_auth: ^6.0.2

  async_redux: ^20.0.2

  get_it: ^7.2.0

  go_router: ^11.1.4

  google_sign_in: ^6.1.6




dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5

  flutter_gen_runner: 5.1.0+1

  json_annotation: any

  json_serializable: any

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg_images/
    - assets/png_images/
